com.atomikos.icatch.service=com.atomikos.icatch.standalone.UserTransactionServiceFactory
com.atomikos.icatch.force_shutdown_on_vm_exit = true
com.atomikos.icatch.automatic_resource_registration = false
com.atomikos.icatch.console_log_level = WARN
# unlike Spring config, this timeout value is in milliseconds, so add 3 zeros
com.atomikos.icatch.max_timeout=1200000
com.atomikos.icatch.output_dir=${catalina.base}/logs/internal_jta
com.atomikos.icatch.log_base_dir=${catalina.base}/logs/internal_jta
