CREATE TABLE PWList (
id int not null auto_increment,
  constraint pk_user primary key (id),
ChapterNo nvarchar(20),
TypeSection nvarchar(20),
TypeFigure nvarchar(20),
Figure_Num nvarchar(50),
Final_Pg_No nvarchar(20),
page_pos nvarchar(50),
Pickup_PrevTextRef nvarchar(150),
P_Num nvarchar(20),
Description nvarchar(1000),
"Kill" nvarchar(20),
Color nvarchar(20),
BW nvarchar(20),
Pict_No nvarchar(200),
DesignSize nvarchar(50),
PhotoSize nvarchar(50),
SourcePhotog nvarchar(500),
Credit nvarchar(500),
Camera_Copy nvarchar(20),
Free nvarchar(20),
RoyaltyFree nvarchar(20),
ObtainedbyAuthor nvarchar(20),
ChapOpener nvarchar(20),
WorkforHire nvarchar(20),
ModelRelease nvarchar(20),
"New" nvarchar(20),
Retain nvarchar(20),
Reuse nvarchar(20),
Archive nvarchar(100),
prodNotes nvarchar(1000),
deptNotes nvarchar(1000),
Company nvarchar(200),
SourceId nvarchar(200),
ISBN nvarchar(20),
status nvarchar(20),
error nvarchar(1000)
);