package com.wiley.sf.common.sql;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import org.junit.Test;

/**
 *
 * @since   JDK 1.6, JUnit 4.10
 * @version 4/23/2012
 * @author  Steve Markoff
 */
public class SelectBeforeInsertTest {

/*--**************** Required SQL setup ********************************

// ---------- mysql
create table SourceTest (
  id int not null auto_increment,
  constraint pk_source_test primary key (id),
  name nvarchar(50) not null
);

alter table SourceTest
  add constraint un_source_t_name unique (name);


// ---------- db2
create table SourceTest (
    id int generated by default as identity (start with 1, increment by 1)
      not null constraint pk_source_test primary key,
    name varchar(50) not null
);

alter table SourceTest
  add constraint un_source_t_name unique (name);

*********************************************************************/

    public static final String NAME = "foo";

    /**
     * @param args
     */
    public static void main(String[] args) throws Exception {
        SelectBeforeInsertTest sbi = new SelectBeforeInsertTest();
        sbi.test();
    }

    @Test
    public void test() throws Exception {
        // read properties file - for now just hardcode
        String driverClass = "com.mysql.jdbc.Driver";
        String connectString ="jdbc:mysql://san-ds-dev.wiley.com/perm_sm";
        String user = "smarkoff";
        String password = "smarkoff";

        SimpleDBConnect dbConnect = new SimpleDBConnect(driverClass,
            connectString, user, password);  // throws various exceptions
        Connection con = dbConnect.getConnection();  // throws SQLException
        Connection con2 = dbConnect.getConnection();  // ditto
        con.setAutoCommit(false);
        con2.setAutoCommit(false);
        int ti = Connection.TRANSACTION_READ_COMMITTED;
        con.setTransactionIsolation(ti);
        con2.setTransactionIsolation(ti);

        // With anything but TRANSACTION_SERIALIZABLE,
        // thread 2 gets to do the insert and thread 1 fails.
        // With TRANSACTION_SERIALIZABLE, thread 2 is forced to wait
        // while thread 1 does the insert, and thread 2 fails.

        // Choices:
        // TRANSACTION_READ_UNCOMMITTED
        // TRANSACTION_READ_COMMITTED
        // TRANSACTION_REPEATABLE_READ
        // TRANSACTION_SERIALIZABLE

        boolean nameExists = nameExists(NAME, con);

        if (nameExists) {
            System.out.println("Thread 1: deleting name...");
            deleteName(NAME, con);
            con.commit();

            nameExists = nameExists(NAME, con);
        }

        Thread2 thread2 = new Thread2(con2);
        thread2.start();

        // wait 3 seconds
        try { Thread.sleep(3000); } catch (InterruptedException ex) { }


        System.out.println("Thread 1: Inserting name...");
        try {
            insertName(NAME, con);
            con.commit();
            System.out.println("Thread 1: Insert comitted.");
        }
        catch (SQLException ex) {
            System.out.print("Thread 1: Caught exception trying to insert name: ");

            // -803 is DB2, 1062 is MySQL
            if (ex.getErrorCode() == -803 || ex.getErrorCode() == 1062) {
                System.out.println("Unique constraint violation");
            }
            else {
                System.out.println(ex);
            }
        }
    }

    public static boolean nameExists(String name, Connection con) throws SQLException {
        PreparedStatement ps = con.prepareStatement("select * from SourceTest where name = ?");
        ps.setString(1, NAME);
        ResultSet rs = ps.executeQuery();
        boolean exists = rs.next();
        ps.close();

        return exists;
    }

    public static void insertName(String name, Connection con) throws SQLException {
        PreparedStatement ps = con.prepareStatement("insert into SourceTest (name) values (?)");
        ps.setString(1, name);
        ps.executeUpdate();
    }

    public static void deleteName(String name, Connection con) throws SQLException {
        PreparedStatement ps = con.prepareStatement("delete from SourceTest where name = ?");
        ps.setString(1, name);
        ps.executeUpdate();
    }
}

class Thread2 extends Thread {
    private final Connection con;

    public Thread2(Connection con) {
        super("Thread-2");
        this.con = con;
    }

    @Override
    public void run() {
        try {
            System.out.println("Thread 2: Inserting name...");
            SelectBeforeInsertTest.insertName(SelectBeforeInsertTest.NAME, con);

            con.commit();
            System.out.println("Thread 2: Insert committed.");
        }
        catch (SQLException ex) {
            System.out.println("Thread 2: Caught exception trying to insert name: ");

            // -803 is DB2, 1062 is MySQL
            if (ex.getErrorCode() == -803 || ex.getErrorCode() == 1062) {
                System.out.println("Unique constraint violation");
            }
            else {
                System.out.println(ex);
            }
        }
    }
}
