package com.wiley.sf.common.sql;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

import org.apache.commons.lang3.BooleanUtils;

/**
 *
 * @since   JDK 1.6
 * @version 4/5/2011
 * @author  Steve Markoff
 */
public class CreateInsertLockWait {

    private final static String TABLE = "DEAD_INSERT";


    public static void main(String [] args) throws Exception {
        if (args.length < 1) {
            System.err.println("Usage: <properties file> [update same rows (yes/no)] [wait seconds]");
            System.exit(1);
        }

        SimpleDBConnect dbConnect = SimpleDBConnect.create(args[0]);
            // throws various exceptions

        boolean sameRows = true;
        if (args.length > 1) {
            sameRows = BooleanUtils.toBoolean(args[1]);
        }

        int waitSecs = 60;
        if (args.length > 2) {
            waitSecs = Integer.parseInt(args[2]);
        }

        CreateInsertLockWait cd = new CreateInsertLockWait(dbConnect.getConnection(), dbConnect.getConnection(), sameRows, waitSecs);
        cd.go();
    }


    private final Connection con1;
    private final Connection con2;
    private final boolean sameRows;
    private final int waitSecs;

    public CreateInsertLockWait(Connection con1, Connection con2, boolean sameRows, int waitSecs) throws SQLException {
        this.con1 = con1;
        this.con2 = con2;
        this.sameRows = sameRows;
        this.waitSecs = waitSecs;
        con1.setTransactionIsolation(Connection.TRANSACTION_READ_COMMITTED);
        con2.setTransactionIsolation(Connection.TRANSACTION_READ_COMMITTED);
        con1.setAutoCommit(false);
        con2.setAutoCommit(false);
    }

    public void go() {
        try {
            deleteAllAndCommit(con1);

            System.out.println("con1 inserting code 'a1'");
            insert(con1, "a1");

            new Thread2(con2).start();

            System.out.println("thread 1 sleeping " + waitSecs + " seconds...");
            Thread.sleep(1000 * waitSecs);

            System.out.println("con1 committing...");
            con1.commit();
        }
        catch (Exception ex) {
            System.out.println("thread 1 caught Exception: " + ex);
        }
    }

    public void runThread2(Connection con) {
        try {
            System.out.println("con2 inserting code 'a1'");
            insert(con, "a1");

            System.out.println("con2 committing...");
            con2.commit();
        }
        catch (Exception ex) {
            System.out.println("thread 2 caught Exception: " + ex);
        }
    }

    private void deleteAllAndCommit(Connection con) throws SQLException {
        String sql = "delete from " + TABLE;
        PreparedStatement ps = con.prepareStatement(sql);
        int rowCount = ps.executeUpdate();
        ps.close();
        con.commit();
    }

    private void insert(Connection con, String code) throws SQLException {
        String sql = "insert into " + TABLE + " (code, name) values (?, ?)";
        PreparedStatement ps = con.prepareStatement(sql);
        ps.setString(1, code);
        ps.setString(2, code);
        int rowCount = ps.executeUpdate();
        ps.close();
    }

    class Thread2 extends Thread {
        private final Connection con;

        public Thread2(Connection con) {
            this.con = con;
        }

        @Override
        public void run() {
            runThread2(con);
        }
    }
}

/**
---- SQL to create tables in DB2:
-- change varchar to nvarchar when db2 supports

create table dead_insert (
  id int not null generated by default as identity
    constraint pk_dead_insert primary key,
  code varchar(20) not null,
  name varchar(100)
);

alter table dead_insert
  add constraint un_insert_code unique (code);

---- SQL to create tables in MySQL:

create table dead_insert (
  id int not null auto_increment,
  constraint pk_dead_insert primary key (id),
  code nvarchar(20) not null,
  name nvarchar(100)
);

alter table dead_insert
  add constraint un_insert_code unique (code);
*/