package com.wiley.sf.common.sql;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

import org.apache.commons.lang3.BooleanUtils;

/**
 *
 * @since   JDK 1.6
 * @version 3/16/2011
 * @author  Steve Markoff
 */
public class CreateDeadlock {

    private final static String PRODUCT_TABLE = "DEAD_PRODUCT";
    private final static String CW_TABLE = "DEAD_COMMON_WORK";


    public static void main(String [] args) throws Exception {
        if (args.length < 1) {
            System.err.println("Usage: <properties file> [update same rows (yes/no)] [wait seconds]");
            System.exit(1);
        }

        SimpleDBConnect dbConnect = SimpleDBConnect.create(args[0]);
            // throws various exceptions

        boolean sameRows = true;
        if (args.length > 1) {
            sameRows = BooleanUtils.toBoolean(args[1]);
        }

        int waitSecs = 2;
        if (args.length > 2) {
            waitSecs = Integer.parseInt(args[2]);
        }

        CreateDeadlock cd = new CreateDeadlock(dbConnect.getConnection(), dbConnect.getConnection(), sameRows, waitSecs);
        cd.go();
    }


    private final Connection con1;
    private final Connection con2;
    private final boolean sameRows;
    private final int waitSecs;

    public CreateDeadlock(Connection con1, Connection con2, boolean sameRows, int waitSecs) throws SQLException {
        this.con1 = con1;
        this.con2 = con2;
        this.sameRows = sameRows;
        this.waitSecs = waitSecs;
        con1.setTransactionIsolation(Connection.TRANSACTION_READ_COMMITTED);
        con2.setTransactionIsolation(Connection.TRANSACTION_READ_COMMITTED);
        con1.setAutoCommit(false);
        con2.setAutoCommit(false);
    }

    public void go() {
        new Thread1(con1).start();
        runThread2(con2);
    }

    public void runThread1(Connection con) {
        System.out.println("thread1: started");

        try {
            updateProduct(con, 1);
            System.out.println("thread1: did first update (Product), waiting " + waitSecs + " seconds");
            try { Thread.sleep(waitSecs * 1000); }
            catch (InterruptedException ex) { }
            System.out.println("thread1: requesting second update (CommonWork)");
            updateCommonWork(con, 1);
            System.out.println("thread1: second update done, requesting commit");
            con.commit();
            System.out.println("thread1: commit done");
        }
        catch (Exception ex) {
            System.out.println("Thread1 Caught Exception: " + ex);
        }
    }

    public void runThread2(Connection con) {
        System.out.println("thread2: started");

        try {
            updateCommonWork(con, (sameRows ? 1 : 2));
            System.out.println("thread2: did first update (CommonWork), waiting " + waitSecs + " seconds");
            try { Thread.sleep(waitSecs * 1000); }
            catch (InterruptedException ex) { }
            System.out.println("thread2: requesting second update (Product)");
            updateProduct(con, (sameRows ? 1 : 2));
            System.out.println("thread2: second update done, requesting commit");
            con.commit();
            System.out.println("thread2: commit done");
        }
        catch (Exception ex) {
            System.out.println("Thread2 Caught Exception: " + ex);
        }
    }


    private void updateCommonWork(Connection con, int cwId) throws SQLException {
        String sql = "update " + CW_TABLE + " set name = ? where id = ?";
        PreparedStatement ps = con.prepareStatement(sql);
        ps.setString(1, "cw" + cwId);
        ps.setInt(2, cwId);
        int rowCount = ps.executeUpdate();
        ps.close();
    }

    private void updateProduct(Connection con, int productId) throws SQLException {
        String sql = "update " + PRODUCT_TABLE + " set title = ? where id = ?";
        PreparedStatement ps = con.prepareStatement(sql);
        ps.setString(1, "p" + productId);
        ps.setInt(2, productId);
        int rowCount = ps.executeUpdate();
        ps.close();
    }

    class Thread1 extends Thread {
        private final Connection con;

        public Thread1(Connection con) {
            this.con = con;
        }

        @Override
        public void run() {
            runThread1(con);
        }
    }
}

/**
---- SQL to create tables in DB2:
-- change varchar to nvarchar when db2 supports

create table dead_common_work (
  id int not null generated by default as identity
    constraint pk_dead_cw primary key,
  name varchar(100)
);

create table dead_product (
  id int not null generated by default as identity
    constraint pk_dead_product primary key,
  title varchar(100) not null,
  cw_id int not null
);

alter table dead_product
  add constraint fk_dead_prod_2_cw foreign key (cw_id) references dead_common_work (id);


---- SQL to create tables in MySQL:

create table dead_common_work (
  id int not null auto_increment,
  constraint pk_dead_cw primary key (id),
  name nvarchar(100)
);

create table dead_product (
  id int not null auto_increment,
  constraint pk_dead_product primary key (id),
  title nvarchar(100) not null,
  cw_id int not null
);

alter table dead_product
  add constraint fk_dead_prod_2_cw foreign key (cw_id) references dead_common_work (id);

---- seed
insert into dead_common_work (id, name) values (1, 'cw1');
insert into dead_common_work (id, name) values (2, 'cw2');

insert into dead_product (title, cw_id) values ('p1', 1);
insert into dead_product (title, cw_id) values ('p2', 2);
*/