package com.wiley.permissions.common.mule;

import javax.jms.JMSException;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.mule.api.MuleMessage;
import org.mule.api.routing.filter.Filter;

//import com.ibm.jms.JMSMessage;
import javax.jms.Message;
/**
 * Custom Mule filter. Will filter the incoming message if CORRELATION_ID is
 * not the same as MESSAGE_ID
 * Seems like processing the message first time, because of the ReplyTo header property,
 * a message is sent to the queue and the inbound is trying to process it again.
 * We have to ignore the second message. The second message has a MESSAGE_ID generated by JMS,
 * not the one sent by PE, so we can use that fact to filter the message
 * @author lnagy
 */
public class JMSMessageFilter implements Filter {

	private static final Log log = LogFactory.getLog(JMSMessageFilter.class);

	@Override
	public boolean accept(MuleMessage message)
	{
		log.debug("-----------------------------------------");
		// smarkoff: Bruce may send XML as is or GZipped
		// If GZipped then Payload will be JMSBytesMessage instead of JMSTextMessage
		// so cast to base class of both (JMSMessage).
		////////JMSMessage jmsMessage = (JMSMessage) message.getPayload();
		Message jmsMessage = (Message) message.getPayload();
		try
		{
			log.debug("ReplyTo " + jmsMessage.getJMSReplyTo());
			String jmsCorrelationId = jmsMessage.getJMSCorrelationID();
			String jmsMessageId = jmsMessage.getJMSMessageID();
			log.debug("CorrelationId  " + jmsCorrelationId);
			log.debug("MessageId  " + jmsMessageId);
			// smarkoff: jmsCorrelationId will be null if send message from Hermes - accept in this case
			boolean accept = jmsMessageId.equalsIgnoreCase(jmsCorrelationId) || jmsCorrelationId == null;
			log.debug("accept(): " + (accept ? "ACCEPT" : "REJECT"));
			return accept;
		}
		catch (JMSException e)
		{
			log.debug("accept(): failed to read message header", e);
		}
		log.debug("-----------------------------------------");
		return false;
	}

}
