transaction.timeout=1200

wiley.ldap.url=ldap://directoryservice.wiley.com:389
wiley.ldap.userDN=CN=Intranet,OU=Plumtree Portal,OU=Wiley Applications,DC=wiley,DC=com
wiley.ldap.password=fhL9vJoO1WxLxgnL
wiley.ldap.base.internal=OU=Wiley Users,DC=wiley,DC=com
wiley.ldap.base.external=OU=Wiley Customers,DC=wiley,DC=com

messaging.jms.pe.inbound.host=VULCAN.WILEY.COM
messaging.jms.pe.inbound.port=21521
messaging.jms.pe.inbound.queueManager=CLIENTRQS.QMGR
messaging.jms.pe.inbound.channel=CLIENT.CONN.CHL
messaging.jms.pe.inbound.transportType=1
messaging.jms.pe.inbound.queue=PERM.FROM.PE

messaging.jms.pe.outbound.host=VULCAN.WILEY.COM
messaging.jms.pe.outbound.port=21521
messaging.jms.pe.outbound.queueManager=CLIENTRQS.QMGR
messaging.jms.pe.outbound.channel=CLIENT.CONN.CHL
messaging.jms.pe.outbound.transportType=1
messaging.jms.pe.outbound.queue=PE.FROM.PERM

messaging.jms.pe.source=PERMISSIONS

messaging.jms.cms.host=VULCAN.WILEY.COM
messaging.jms.cms.port=21521
messaging.jms.cms.queueManager=CLIENTRQS.QMGR
messaging.jms.cms.channel=CLIENT.CONN.CHL
messaging.jms.cms.transportType=1
messaging.jms.cms.enabled=false

messaging.jms.cms.inbound.queue=PERM.FROM.CMS
messaging.jms.cms.outbound.queue=CMS.FROM.PERM

outgoing.messages.enabled=true
messaging.pe.outgoing.default.bunchlimit=20

#################################################################
#																#
#			 PERMISSION DATABASE(PERM) PROPERTIES 				#
#																#
#################################################################
perm.db.driver=com.mysql.cj.jdbc.Driver
perm.db.xadriver=com.mysql.cj.jdbc.MysqlXADataSource
perm.db.server=aus-lndbgpsp-01.wiley.com
perm.db.databaseName=perm
perm.db.user=permuser
perm.db.password=permuser
perm.db.url=jdbc:mysql://aus-lndbgpsp-01.wiley.com:3322/perm
perm.db.dialect=org.hibernate.dialect.MySQLInnoDBDialect
perm.db.minPoolSize=10
perm.db.maxPoolSize=30
perm.db.testQuery=select current_timestamp

# We have 3 extra slots to fill - if don't need all 3 then just repeat a previous one
perm.db.extra.name1=portNumber
perm.db.extra.value1=3322
perm.db.extra.name2=pinGlobalTxToPhysicalConnection
perm.db.extra.value2=true
perm.db.extra.name3=pinGlobalTxToPhysicalConnection
perm.db.extra.value3=true

#################################################################
#																#
#			 WINTOUCH DATABASE PROPERTIES		 				#
#																#
#################################################################
wintouch.db.driver=com.mysql.cj.jdbc.Driver
wintouch.db.xadriver=com.mysql.cj.jdbc.MysqlXADataSource
wintouch.db.server=aus-lndbgpsp-01.wiley.com
wintouch.db.databaseName=wintouch
wintouch.db.user=permuser
wintouch.db.password=permuser
wintouch.db.url=jdbc:mysql://aus-lndbgpsp-01.wiley.com:3322/wintouch
wintouch.db.dialect=org.hibernate.dialect.MySQLInnoDBDialect
wintouch.db.minPoolSize=5
wintouch.db.maxPoolSize=20
wintouch.db.testQuery=select current_timestamp

# We have 3 extra slots to fill - if don't need all 3 then just repeat a previous one
wintouch.db.extra.name1=portNumber
wintouch.db.extra.value1=3322
wintouch.db.extra.name2=pinGlobalTxToPhysicalConnection
wintouch.db.extra.value2=true
wintouch.db.extra.name3=pinGlobalTxToPhysicalConnection
wintouch.db.extra.value3=true

#################################################################
#																#
#			 EMAIL SETTINGS		 								#
#																#
#################################################################
email.smtp.server=smtpgate.wiley.com

#################################################################
#																#
#			 COMP COPY INTEGRATION 								#
#																#
#################################################################
comp.copy.request.url=http://customerq.wiley.com/CGI-BIN/lansaweb?procfun+shopcart3+sh3fn27+funcparms+acct13(a0130):0158280900000
comp.copy.request.au.url=http://dev-ebusiness.johnwiley.com.au/CGI-BIN/lansaweb?procfun+shopcart3+sh3fn27+funcparms

#################################################################
#																#
#			 OUT OF COMPLIANCE	 								#
#																#
#################################################################
contract.before.expire.days=20

#################### WEB SETTINGS
#internal.url and author.url should be the SSO url - not direct to Tomcat
internal.url=http://permissions.wiley.com
author.url=http://permissions.wiley.com/author-web/
rest.port.internal=63082
rest.url.internal=http://permissionprod.wiley.com:63082
rest.url.external=http://permissions.wiley.com:63082

# Certain things avoid running in "primeTime" - currently this is just the AssetUse index build
# If you want to effectively not have a primeTime window, set start/stop to same value
# 19 = 7pm
primeTime.startHour=8
primeTime.stopHour=19

################## RightsLink settings
rightslink.tokenUri = https://api.copyright.com/token
rightslink.licenseUri = https://api.copyright.com/rlnk/1.0/licenses/
rightslink.username = wiley_gps@wiley.com
rightslink.password = wiley1
# sandbox values
#rightslink.consumerKey = D3uB47Y5CQ9zqTWVHQLgqrRZQksa
#rightslink.consumerSecret = 5jSEWUKk_5iAGvgqbkvsGTVXpDIa
# production values
rightslink.consumerKey = dd0tsEXk8exXWK7LdQzzoAgsPgEa
rightslink.consumerSecret = T5DGGE1RmOn9dImbyjWHU56CVcsa
# scope should be either SANDBOX or PRODUCTION
rightslink.scope = PRODUCTION
