# This file is no longer used - only kept in case we need an example of DB2 configuration

transaction.timeout=1200

wiley.ldap.url=ldap://directoryservice.wiley.com:389
wiley.ldap.userDN=CN=Intranet,OU=Plumtree Portal,OU=Wiley Applications,DC=wiley,DC=com
wiley.ldap.password=fhL9vJoO1WxLxgnL
wiley.ldap.base.internal=OU=Wiley Users,DC=wiley,DC=com
wiley.ldap.base.external=OU=Wiley Customers,DC=wiley,DC=com

messaging.jms.pe.inbound.host=MARS.WILEY.COM
messaging.jms.pe.inbound.port=25200
messaging.jms.pe.inbound.queueManager=DEVELOPER.QMGR
messaging.jms.pe.inbound.channel=DEV.SERVER.CHL
messaging.jms.pe.inbound.transportType=1
messaging.jms.pe.inbound.queue=SMPERM.FROM.PE

messaging.jms.pe.outbound.host=MARS.WILEY.COM
messaging.jms.pe.outbound.port=21521
messaging.jms.pe.outbound.queueManager=CLIENTRQS.QMGR
messaging.jms.pe.outbound.channel=CLIENT.CONN.CHL
messaging.jms.pe.outbound.transportType=1
messaging.jms.pe.outbound.queue=PE.FROM.PERM

messaging.jms.pe.source=PERMSM

#messaging.jms.cms.host=MARS.WILEY.COM
#messaging.jms.cms.port=21521
#messaging.jms.cms.queueManager=CLIENTRQS.QMGR
#messaging.jms.cms.channel=CLIENT.CONN.CHL
#messaging.jms.cms.transportType=1
#messaging.jms.cms.inbound.queue=PERM.FROM.CMS
#messaging.jms.cms.outbound.queue=CMS.FROM.PERM

messaging.jms.cms.host=MARS.WILEY.COM
messaging.jms.cms.port=25200
messaging.jms.cms.queueManager=DEVELOPER.QMGR
messaging.jms.cms.channel=DEV.SERVER.CHL
messaging.jms.cms.transportType=1
messaging.jms.cms.enabled=false

messaging.jms.cms.inbound.queue=SMPERM.FROM.CMS
messaging.jms.cms.outbound.queue=SMCMS.FROM.PERM

outgoing.messages.enabled=true
messaging.pe.outgoing.default.bunchlimit=20

#################################################################
#																#
#			 PERMISSION DATABASE(PERM) PROPERTIES 				#
#																#
#################################################################
perm.db.driver=com.ibm.db2.jcc.DB2Driver
perm.db.xadriver=com.ibm.db2.jcc.DB2XADataSource
perm.db.server=san-ds-dev.wiley.com
perm.db.databaseName=perm
perm.db.user=smarkoff
perm.db.password=smarkoff
perm.db.url=jdbc:db2://san-ds-dev.wiley.com:50000/PERM
perm.db.dialect=org.hibernate.dialect.DB2Dialect
perm.db.minPoolSize=2
perm.db.maxPoolSize=10
perm.db.testQuery=select current timestamp from SYSIBM.SYSDUMMY1

# We have 3 extra slots to fill - if don't need all 3 then just repeat a previous one
perm.db.extra.name1=portNumber
perm.db.extra.value1=50000
perm.db.extra.name2=driverType
perm.db.extra.value2=4
perm.db.extra.name3=driverType
perm.db.extra.value3=4

#################################################################
#																#
#			 WINTOUCH DATABASE PROPERTIES		 				#
#																#
#################################################################
wintouch.db.driver=com.ibm.db2.jcc.DB2Driver
wintouch.db.xadriver=com.ibm.db2.jcc.DB2XADataSource
wintouch.db.server=san-ds-dev.wiley.com
wintouch.db.databaseName=PERM
wintouch.db.user=smarkoff
wintouch.db.password=smarkoff
wintouch.db.url=jdbc:db2://san-ds-dev.wiley.com:50000/PERM
wintouch.db.dialect=org.hibernate.dialect.DB2Dialect
wintouch.db.minPoolSize=2
wintouch.db.maxPoolSize=10
wintouch.db.testQuery=select current timestamp from SYSIBM.SYSDUMMY1

# We have 3 extra slots to fill - if don't need all 3 then just repeat a previous one
wintouch.db.extra.name1=portNumber
wintouch.db.extra.value1=50000
wintouch.db.extra.name2=driverType
wintouch.db.extra.value2=4
wintouch.db.extra.name3=driverType
wintouch.db.extra.value3=4

#################################################################
#																#
#			 EMAIL SETTINGS		 								#
#																#
#################################################################
email.smtp.server=smtpgate.wiley.com

#################################################################
#																#
#			 COMP COPY INTEGRATION 								#
#																#
#################################################################
comp.copy.request.url=http://customerq.wiley.com/CGI-BIN/lansaweb?procfun+shopcart3+sh3fn27+funcparms+acct13(a0130):0158280900000
comp.copy.request.au.url=http://dev-ebusiness.johnwiley.com.au/CGI-BIN/lansaweb?procfun+shopcart3+sh3fn27+funcparms

#################################################################
#																#
#			 OUT OF COMPLIANCE	 								#
#																#
#################################################################
contract.before.expire.days=20

#################### WEB SETTINGS
#internal.url and author.url should be the SSO url - not direct to Tomcat
# - but there is no SSO url for developers
internal.url=http://localhost:8080
author.url=http://localhost:8080/author-web/
rest.port.internal=63082
rest.url.internal=http://localhost:63082
rest.url.external=http://localhost:63082
