driverClass = com.ibm.as400.access.AS400JDBCDriver
connectString = jdbc:as400://ap2dev.wiley.com/permisslib
user = permuser
password = permuser1
driverJarFile = /home/smarkoff/jt400-jdbc40-6.7.jar
extra1.name =
extra2.value =
    
environment.name = DEV
fileIOBench.dir = /spare/permissions/iobench
