driverClass = com.ibm.as400.access.AS400JDBCDriver
connectString = jdbc:as400://ap2dev.wiley.com/permisslib
user = permuser
password = permuser1
driverJarFile = C:/javalib/jtopen_6_7/lib/jt400.jar
extra1.name =
extra2.value =
    
environment.name = DEV
