driverClass = com.microsoft.sqlserver.jdbc.SQLServerDriver
connectString = jdbc:sqlserver://SAN-DB-SQL2008;databaseName=perm
user = perm
password = hark4S
driverJarFile = C:/lib/sqljdbc4.jar
extra1.name =
extra2.value =

environment.name = Control
