driverClass = com.ibm.db2.jcc.DB2Driver
connectString = jdbc:db2://san-ds-dev.wiley.com:50000/PERM
user = smarkoff
password = smarkoff
driverJarFile = C:\\lib\\db2jcc4.jar
extra1.name =
extra2.value =
