driverClass = oracle.jdbc.OracleDriver
connectString = jdbc:oracle:thin:@dev3.wiley.com:1558:GLOBAL
user = global_admin
password = global_admin
driverJarFile = C:\\lib\\ojdbc6.jar
extra1.name =
extra2.value =
