driverClass = com.microsoft.sqlserver.jdbc.SQLServerDriver
connectString = jdbc:sqlserver://localhost;databaseName=benchmark
user = smarkoff
password = smarkoff
driverJarFile = C:\\lib\\sqljdbc4.jar
extra1.name =
extra2.value =
